### ISSUE TITLE
sample project not work 

### ISSUE THREAD

**Issue by shehabso** [deltalejo/ceedling-cppcheck-example#1]
i am not able to run cppcheck for misra rule in ceedling 
could you support me ?
steps 
1- clone  ceedling-cppcheck-example .
2-ensure cppcheck work correct and add it in the environmental path .
3- run ceedling stand alone . 

output :

C:\Users\shehab_tarek\Desktop\github_repo\ceedling-cppcheck-example>ceedling cppcheck 
ERROR: Ceedling plugin 'report_tests_pretty_stdout' contains no rake or ruby class entry point. (Misspelled or missing files?)
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/configurator.rb:309:in `validate': unhandled exception
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/setupinator.rb:32:in `do_setup'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/rakefile.rb:47:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling.rb:66:in `load'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling.rb:66:in `load_project'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/bin/ceedling:329:in `<top (required)>'
        from C:/Ruby30-x64/bin/ceedling:25:in `load'
        from C:/Ruby30-x64/bin/ceedling:25:in `<main>'

**Comment by deltalejo** [comment]
It seems you are using Ceedling 0.31.1, try with latest prerelease 1.0.0.
If you need to stay at 0.31.1, maybe try checking out commit `07f5585e88071eb6aafd70dd5ae6074c33291c85` of this project and updating submodules.
e.g:
```shell
git checkout 07f5585e88071eb6aafd70dd5ae6074c33291c85
git submodule update
```

**Comment by shehabso** [comment]
are you work on  Linux or windows machine   ?
 TODO : i am sure  add cppcheck in the environmental path 
  and i will check at different pc 
ERROR: Config filepath [:tools][:cppcheck][:executable]['cppcheck.exe'] does not exist in system search paths.
ERROR: Ceedling plugin 'report_tests_pretty_stdout' contains no rake or ruby class entry point. (Misspelled or missing files?)
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/configurator.rb:309:in `validate': unhandled exception    
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/setupinator.rb:32:in `do_setup'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/rakefile.rb:47:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling.rb:66:in `load'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling.rb:66:in `load_project'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/bin/ceedling:329:in `<top (required)>'
        from C:/Ruby30-x64/bin/ceedling:25:in `load'
        from C:/Ruby30-x64/bin/ceedling:25:in `<main>'

**Comment by deltalejo** [comment]
I work on a Linux machine, honestly I've never tried this out on a Windows one.
Try with this commit `faa49770b1fd352b8cb5cb2fb83b5164e2ef110c`.
It seems that I updated the project for the upcoming Ceedling release some time ago now.

**Comment by deltalejo** [comment]
You may want to add Cppcheck path to your `project.yml`:
```yaml
:environment:
  - :path:
    - path/where/cppcheck/is/located
    - "#{ENV['PATH']}"
```

**Comment by shehabso** [comment]
Check the repo at 
`https://github.com/shehabso/testingSchool`

I am using a CI pipeline with Ceedling. My question is, if the problem occurs on Windows, can you fork this repo and set up the project on the pipeline?
OR  
Can you show me how the project runs in CI by adding a workflow to your repo?

**Comment by deltalejo** [comment]
Were you able to run this sample project locally with the suggestions above?
What error are you seeing now?
If you are setting your own project, I'd suggest working directly with the [Cppcheck Plugin](https://github.com/deltalejo/ceedling-cppcheck-plugin).

**Comment by shehabso** [comment]
the error 

the problem occur when i enable the cppcheck from project. yml file 





Run ceedling test:all gcov:all
  
ERROR: Ceedling plugin 'cppcheck' contains no rake or ruby class entry point. (Misspelled or missing files?)
/opt/hostedtoolcache/Ruby/3.0.7/x6[4](https://github.com/shehabso/testingSchool/actions/runs/11921913993/job/33227068659#step:6:4)/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/configurator.rb:309:in `validate': unhandled exception
	from /opt/hostedtoolcache/Ruby/3.0.7/x6[4](https://github.com/shehabso/testingSchool/actions/runs/11921913993/job/33227068659#step:6:5)/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/setupinator.rb:32:in `do_setup'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/rakefile.rb:47:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling.rb:66:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling.rb:66:in `load_project'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.1/bin/ceedling:329:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/bin/ceedling:2[5](https://github.com/shehabso/testingSchool/actions/runs/11921913993/job/33227068659#step:6:6):in `load'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/bin/ceedling:25:in `<main>'
	



:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build

  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

:test_build:
  :use_assembly: FALSE



:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90


:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report      #nice test results at your command line

    - warnings_report
    - module_generator
    - gcov
    - command_hooks
    - module_generator
    - cppcheck

:cppcheck:
  :reports:
    - text
    - xml
    - html
  :standard: c99
  :inline_suppressions: true
  :addons:
    - misra

**Comment by deltalejo** [comment]
Have you followed the [instructions](https://github.com/deltalejo/ceedling-cppcheck-plugin?tab=readme-ov-file#installation) for adding the Cppcheck plugin to your project? It seems that you are missing it from your project.

**Comment by shehabso** [comment]
Yes I follow all the instructions  please make workflow  ci for the project .

**Comment by deltalejo** [comment]
I cannot see the cppcheck plugin sources on your repo. Please add them to it.
As you are using Ceedling 0.31.1, checkout the 0.31 branch.
e.g.: `git clone -b ceedling-0.31 https://github.com/deltalejo/ceedling-cppcheck-plugin.git somewhere/in/your/project`

**Comment by deltalejo** [comment]
You may want to add it as a submodule. From your repo root:
```shell
mkdir -p vendor/ceedling/plugins
git submodule add -b ceedling-0.31 https://github.com/deltalejo/ceedling-cppcheck-plugin.git vendor/ceedling/plugins/cppcheck
```
I see you are working from `Mock/blinky`, so add to its `project.yml` the plugin path.
e.g.:
```yaml
:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
    - ../../vendor/ceedling/plugins
```
